# Generated by Django 5.2.8 on 2026-01-23 12:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0004_crosstrackprogramprogress_crosstracksubmission'),
    ]

    operations = [
        # Add slug and title fields to curriculum_tracks
        migrations.AddField(
            model_name='curriculumtrack',
            name='slug',
            field=models.SlugField(
                blank=True,
                help_text='URL-friendly identifier',
                max_length=100,
                null=True
            ),
        ),
        migrations.AddField(
            model_name='curriculumtrack',
            name='title',
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True
            ),
        ),

        # Add curriculum_level field to curriculummodules
        migrations.AddField(
            model_name='curriculummodule',
            name='curriculum_level',
            field=models.ForeignKey(
                blank=True,
                help_text='FK to CurriculumLevel',
                null=True,
                on_delete=models.SET_NULL,
                related_name='modules',
                to='curriculum.curriculumlevel'
            ),
        ),

        # Add supporting_recipes field to curriculummodules
        migrations.AddField(
            model_name='curriculummodule',
            name='supporting_recipes',
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='Recipe slugs that support this module'
            ),
        ),

        # Create new models
        migrations.CreateModel(
            name='CurriculumLevel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(help_text='URL-friendly identifier (beginner, intermediate, etc.)')),
                ('title', models.CharField(help_text='Level title (Beginner, Intermediate, etc.)', max_length=255)),
                ('description', models.TextField(blank=True)),
                ('order_number', models.IntegerField(default=0, help_text='Order within track')),
                ('estimated_duration_hours', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('track', models.ForeignKey(
                    on_delete=models.CASCADE,
                    related_name='levels',
                    to='curriculum.curriculumtrack'
                )),
            ],
            options={
                'verbose_name': 'Curriculum Level',
                'verbose_name_plural': 'Curriculum Levels',
                'db_table': 'curriculum_levels',
                'unique_together': {('track', 'slug')},
                'ordering': ['track', 'order_number'],
            },
        ),

        migrations.CreateModel(
            name='CurriculumVideo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(help_text='URL-friendly identifier', max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('video_url', models.URLField(blank=True, help_text='Video URL or placeholder')),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('order_number', models.IntegerField(default=0, help_text='Order within module')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('module', models.ForeignKey(
                    on_delete=models.CASCADE,
                    related_name='videos',
                    to='curriculum.curriculummodule'
                )),
            ],
            options={
                'verbose_name': 'Curriculum Video',
                'verbose_name_plural': 'Curriculum Videos',
                'db_table': 'curriculum_videos',
                'unique_together': {('module', 'slug')},
                'ordering': ['module', 'order_number'],
            },
        ),

        migrations.CreateModel(
            name='CurriculumQuiz',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(help_text='URL-friendly identifier', max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('questions', models.JSONField(help_text='Quiz questions and answers in JSON format')),
                ('pass_threshold', models.IntegerField(default=80, help_text='Passing percentage (0-100)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('module', models.ForeignKey(
                    on_delete=models.CASCADE,
                    related_name='quizzes',
                    to='curriculum.curriculummodule'
                )),
            ],
            options={
                'verbose_name': 'Curriculum Quiz',
                'verbose_name_plural': 'Curriculum Quizzes',
                'db_table': 'curriculum_quizzes',
                'unique_together': {('module', 'slug')},
            },
        ),

        migrations.CreateModel(
            name='StrategicSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('agenda_items', models.JSONField(blank=True, default=list, help_text='Session agenda items')),
                ('estimated_duration_minutes', models.IntegerField(default=90)),
                ('supporting_recipes', models.JSONField(blank=True, default=list, help_text='Recipe slugs for session')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('level', models.ForeignKey(
                    on_delete=models.CASCADE,
                    related_name='strategic_sessions',
                    to='curriculum.curriculumlevel'
                )),
            ],
            options={
                'verbose_name': 'Strategic Session',
                'verbose_name_plural': 'Strategic Sessions',
                'db_table': 'strategic_sessions',
                'ordering': ['level', 'created_at'],
            },
        ),
    ]
